# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a185373ae5db6d13ee947961492cfcd569cb4842fab6f383253cf73c14b63820e74c93078079b120f2ae5a53f38de2ed5d1b48aa21481c76bcfcdeaff806b13c

test:
  secret_key_base: 9427e02c92766297fe926f7c41536c978e2716aa6b61b9cb2f5f6ddacaf002f5803dcbe86013d28ae83b71821ab40699b501d18e68151f706d1b15d54a6c825a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
